### ISSUE TITLE
02-02 - fizzbuzz

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/js#1]
na wstepie:
. masz blad w linii drugiej - uzywasz & (co jest bitwise AND) zamiast && (logiczny AND). w tym wypadku akurat to bangla, w innych moze nie zadzialac
. przerob to prosze na funkcje, ktora bedzie mogla przyjmowac dowolna liczbe koncowa
. postaraj sie tak przepisac warunki, zeby byly tylko 2 ify (bez zadnego else)

zeby osiagnac punkt drugi dam Ci pare podpowiedzi:
. zrob tylko jeden punkty wyjscia, tzn tylko jeden console.log() na iteracje petli
. console.log(wyrazenie) wyrzuca do konsoli wartosc wyrazenia, tzn jezeli zamiast wyrazenie wstawisz 2 + 3 wypisze Ci 5, wyrazenie = 'a' + 'b' => 'ab', wyrazenie = 3 > 2 => true
. operator || (OR) w javascriptcie dziala tak, ze x || y:
a) jezeli x jest prawdziwe - zwraca x
b) jezeli x jest falszywe - zwraca y
. przeczytaj jakie wartosci sa falsy w jsie: http://ferrante.pl/frontend/javascript/falsy-values-i-operatory-porownania/

**Comment by konradkukier2** [comment]
done
