### ISSUE TITLE
04-extra

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/js#8]
skad to wziales?

**Comment by konradkukier2** [comment]
w 4 rozdziale Eloquent JS jest przyklad, w ktorym tworzona jest tabela, ktora zbiera dane z dziennika/logu tak zeby mozna bylo je potem skorelowac. W ksiazce funkcja nazywa sie tableFor. W moim kodzie na dole, wkleilem zreszta orginal. Nie moglem go zalapac, ale po napisaniu swojej wersji (mimo, ze gorszej) - zalapalem kazda linijke. A skoro juz zrobilem, to wrzucilem na Gita.
