### ISSUE TITLE
dodatkowe - count

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/js#9]
element z reducem masz zle napisany. nie wykorzystujesz mozliwosci reduce.

+ staraj sie tak formatowac kod:
.forEach(function(..) {
   ....
});

**Comment by lsiedlaczek** [comment]
tam powinny byc nowe linie po { i przed }

**Comment by konradkukier2** [comment]
No to albo nie lapie tego formatowania, albo dokladnie tak wlasnie mialem.

Anyways, .reduce poprawiony. Powinien byc ok.
